parameters:
    snowio_connector.job_parameters.form_configuration_provider.product.class: Snowio\Bundle\CsvConnectorBundle\Job\JobParameters\FormConfigurationProvider\ProductCsvExport
    snowio_connector.job_parameters.form_configuration_provider.simple.class: Snowio\Bundle\CsvConnectorBundle\Job\JobParameters\FormConfigurationProvider\SimpleCsvExport

services:
    snowio_connector.job_parameters.form_configuration_provider.complete_export:
        class: '%snowio_connector.job_parameters.form_configuration_provider.product.class%'
        arguments:
            - '@pim_import_export.job_parameters.form_configuration_provider.simple_csv_export'
            - ['complete_export']
            - '%pim_catalog.localization.decimal_separators%'
            - '%pim_catalog.localization.date_formats%'
        tags:
            - { name: pim_import_export.job_parameters.form_configuration_provider }

    snowio_connector.job_parameters.form_configuration_provider.incomplete_export:
        class: '%snowio_connector.job_parameters.form_configuration_provider.simple.class%'
        arguments:
            - ['incomplete_export']
        tags:
            - { name: pim_import_export.job_parameters.form_configuration_provider }
