services:

    guzzlehttp.client:
        class: %guzzlehttp.client%

    snowio.source.handlerType:
        class: %snowio.source.handlerType%

    snowio_csv_connector.handler.post:
        class: %snowio_csv_connector.handler.post.class%
        arguments:
            - @guzzlehttp.client
            - @snowio.source.handlerType
