services:
    snowio_connector.provider.form.job_instance:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                complete_export: snowio-job-instance-csv-product-export
                incomplete_export: snowio-job-instance-csv-export
        tags:
            - { name: pim_enrich.provider.form, priority: 100 }
